MAX_TOKENS = 256          # max new tokens per prompt
TEMPERATURE = 0.0         # greedy decoding (do_sample=False)
TIMEOUT_SECONDS = 1200     # 20-minute wall-clock timeout for full run
DRY_RUN_PROMPTS = 3       # number of prompts for dry-run validation
SEED = 42
NUM_PROMPTS = 50          # total prompts generated by setup.py
